
#-*- coding: utf-8 -*-
'''
  <auto-generated>
    This code was generated by a tool.
    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
  </auto-generated>
'''

from enum import Enum



class 参数 :
    def __init__(self, _json_):
        self.参数值 = _json_['参数值']

class 基础数据_怪物设计表 :
    def __init__(self, _json_):
        self.怪物编号 = _json_['怪物编号']
        self.品质 = _json_['品质']
        self.职业 = _json_['职业']
        self.名称 = _json_['名称']
        self.等级 = _json_['等级']
        self.血量 = _json_['血量']
        self.攻击力 = _json_['攻击力']
        self.攻速 = _json_['攻速']
        self.攻击范围 = _json_['攻击范围']
        self.移动速度 = _json_['移动速度']
        self.DPS = _json_['DPS']
        self.血量特效倍率 = _json_['血量特效倍率']
        self.DPS特效倍率 = _json_['DPS特效倍率']
        self.战力 = _json_['战力']
        self.血量成长倍率 = _json_['血量成长倍率']
        self.攻击力成长倍率 = _json_['攻击力成长倍率']
        self.适配地图 = _json_['适配地图']
        self.对塔伤害 = _json_['对塔伤害']

class 基础数据_角色初始属性表 :
    def __init__(self, _json_):
        self.角色名称 = _json_['角色名称']
        self.攻击属性 = _json_['攻击属性']
        self.品质 = _json_['品质']
        self.职业 = _json_['职业']
        self.最大等级 = _json_['最大等级']
        self.期望生命周期 = _json_['期望生命周期']
        self.初始血量 = _json_['初始血量']
        self.血量成长倍率 = _json_['血量成长倍率']
        self.初始攻击力 = _json_['初始攻击力']
        self.攻击力成长倍率 = _json_['攻击力成长倍率']
        self.初始攻速 = _json_['初始攻速']
        self.攻速成长倍率 = _json_['攻速成长倍率']
        self.初始攻击范围 = _json_['初始攻击范围']
        self.攻击范围成长倍率 = _json_['攻击范围成长倍率']
        self.初始移速 = _json_['初始移速']
        self.移速成长倍率 = _json_['移速成长倍率']
        self.血量特效战力系数 = _json_['血量特效战力系数']
        self.DPS特效战力系数 = _json_['DPS特效战力系数']
        self.对塔伤害 = _json_['对塔伤害']

class 基础数据_角色技能数据表 :
    def __init__(self, _json_):
        self.角色名称 = _json_['角色名称']
        self.各等级技能倍率 = {};
        for _elek0_, _elev0_ in _json_['各等级技能倍率']:
            _k0_ = _elek0_
            _v0_ = 角色技能倍率(_elev0_)
            self.各等级技能倍率[_k0_] = _v0_

class 基础数据_经济系统配置表 :
    def __init__(self, _json_):
        self.经济系统 = _json_['经济系统']
        self.经济系统数据 = {};
        for _elek0_, _elev0_ in _json_['经济系统数据']:
            _k0_ = _elek0_
            _v0_ = 资源数据(_elev0_)
            self.经济系统数据[_k0_] = _v0_
        self.钻石价格 = _json_['钻石价格']
        self.购买次数 = _json_['购买次数']
        self.获得次数 = _json_['获得次数']

class 基础数据_肉鸽技能数据表 :
    def __init__(self, _json_):
        self.肉鸽技能名称 = _json_['肉鸽技能名称']
        self.血量加成 = _json_['血量加成']
        self.攻击力加成 = _json_['攻击力加成']
        self.攻速加成 = _json_['攻速加成']
        self.消除倍率 = _json_['消除倍率']
        self.每块小兵增加期望值 = _json_['每块小兵增加期望值']
        self.选中概率 = _json_['选中概率']
        self.技能流派 = _json_['技能流派']

class 基础数据_玩家操作评估 :
    def __init__(self, _json_):
        self.平均一个方块下几秒 = _json_['平均一个方块下几秒']
        self.平均一秒下几个方块 = _json_['平均一秒下几个方块']
        self.每个方块的小方块数 = _json_['每个方块的小方块数']
        self.每行能放几个小方块 = _json_['每行能放几个小方块']
        self.玩家1分钟下方块数 = _json_['玩家1分钟下方块数']
        self.玩家10分钟下方块数 = _json_['玩家10分钟下方块数']
        self.消除效率 = _json_['消除效率']
        self.玩家10分钟消除方块数 = _json_['玩家10分钟消除方块数']
        self.小方块经验值 = _json_['小方块经验值']
        self.玩家1分钟获得经验值 = _json_['玩家1分钟获得经验值']
        self.玩家10分钟获得经验值 = _json_['玩家10分钟获得经验值']
        self.平均每个方块小兵数 = _json_['平均每个方块小兵数']
        self.玩家每秒下几个兵 = _json_['玩家每秒下几个兵']
        self.玩家每秒消除几行 = _json_['玩家每秒消除几行']
        self.玩家每秒获取经验速度 = _json_['玩家每秒获取经验速度']
        self.玩家每分获取经验速度 = _json_['玩家每分获取经验速度']
        self.玩家10分钟消除总行数 = _json_['玩家10分钟消除总行数']

class 基础数据_消除倍率表 :
    def __init__(self, _json_):
        self.消除效率维度 = _json_['消除效率维度']
        self.消除参数 = {};
        for _elek0_, _elev0_ in _json_['消除参数']:
            _k0_ = _elek0_
            _v0_ = 参数(_elev0_)
            self.消除参数[_k0_] = _v0_

class 基础数据_游戏基本参数 :
    def __init__(self, _json_):
        self.每个方块的小方块数 = _json_['每个方块的小方块数']
        self.小方块经验值 = _json_['小方块经验值']
        self.角色等级上限 = _json_['角色等级上限']
        self.最大上阵角色数 = _json_['最大上阵角色数']
        self.角色品质划分 = _json_['角色品质划分']
        self.战场总长度 = _json_['战场总长度']
        self.一般默认移动速度 = _json_['一般默认移动速度']
        self.关卡时长 = _json_['关卡时长']
        self.肉鸽技能选择次数 = _json_['肉鸽技能选择次数']
        self.怪物波次间隔 = _json_['怪物波次间隔']
        self.坦克生存时间 = _json_['坦克生存时间']
        self.近战生存时间 = _json_['近战生存时间']
        self.远程生存时间 = _json_['远程生存时间']
        self.刺客生存时间 = _json_['刺客生存时间']
        self.平均生存时间 = _json_['平均生存时间']
        self.属性换算比例 = _json_['属性换算比例']
        self.血量战力价值 = _json_['血量战力价值']
        self.DPS战力价值 = _json_['DPS战力价值']
        self.最大行数 = _json_['最大行数']
        self.最大列数 = _json_['最大列数']
        self.每行经验值 = _json_['每行经验值']
        self.绿色强度 = _json_['绿色强度']
        self.蓝色强度 = _json_['蓝色强度']
        self.紫色强度 = _json_['紫色强度']
        self.绿色成长倍率 = _json_['绿色成长倍率']
        self.蓝色成长倍率 = _json_['蓝色成长倍率']
        self.紫色成长倍率 = _json_['紫色成长倍率']
        self.绿色角色1级战力 = _json_['绿色角色1级战力']
        self.平均肉鸽技能倍率 = _json_['平均肉鸽技能倍率']

class 角色技能倍率 :
    def __init__(self, _json_):
        self.血量倍率 = _json_['血量倍率']
        self.DPS倍率 = _json_['DPS倍率']
        self.血量特效倍率 = _json_['血量特效倍率']
        self.DPS特效倍率 = _json_['DPS特效倍率']
        self.技能名称 = _json_['技能名称']
        self.技能描述 = _json_['技能描述']

class 生成数据_怪物基础数据表_3导 :
    def __init__(self, _json_):
        self.怪物名称等级 = _json_['怪物名称等级']
        self.怪物编号 = _json_['怪物编号']
        self.等级 = _json_['等级']
        self.血量 = _json_['血量']
        self.攻击力 = _json_['攻击力']
        self.攻速 = _json_['攻速']
        self.攻击范围 = _json_['攻击范围']
        self.移动速度 = _json_['移动速度']
        self.DPS = _json_['DPS']
        self.血量特效倍率 = _json_['血量特效倍率']
        self.DPS特效倍率 = _json_['DPS特效倍率']
        self.战力 = _json_['战力']
        self.品质 = _json_['品质']
        self.职业 = _json_['职业']
        self.名称 = _json_['名称']
        self.血量成长倍率 = _json_['血量成长倍率']
        self.攻击力成长倍率 = _json_['攻击力成长倍率']
        self.适配地图 = _json_['适配地图']
        self.对塔伤害 = _json_['对塔伤害']
        self.和理论值对比 = _json_['和理论值对比']

class 生成数据_关卡设计表_1导 :
    def __init__(self, _json_):
        self.关卡编号 = _json_['关卡编号']
        self.阵容强度 = _json_['阵容强度']
        self.绿色等级 = _json_['绿色等级']
        self.蓝色等级 = _json_['蓝色等级']
        self.紫色等级 = _json_['紫色等级']
        self.关卡难度 = _json_['关卡难度']
        self.适配地图 = _json_['适配地图']

class 生成数据_技能型Boss属性表_3导 :
    def __init__(self, _json_):
        self.名称 = _json_['名称']
        self.编号 = _json_['编号']
        self.技能等级 = _json_['技能等级']
        self.血量 = _json_['血量']
        self.移动速度 = _json_['移动速度']
        self.适配地图 = _json_['适配地图']
        self.对塔伤害 = _json_['对塔伤害']

class 生成数据_角色成长数据_1导 :
    def __init__(self, _json_):
        self.角色名称 = _json_['角色名称']
        self.品质 = _json_['品质']
        self.职业 = _json_['职业']
        self.等级 = _json_['等级']
        self.血量 = _json_['血量']
        self.攻击力 = _json_['攻击力']
        self.攻击速度_S = _json_['攻击速度_S']
        self.攻击范围_格 = _json_['攻击范围_格']
        self.移速_格_S = _json_['移速_格_S']
        self.基础DPS = _json_['基础DPS']
        self.血量战力 = _json_['血量战力']
        self.DPS战力 = _json_['DPS战力']
        self.血量特效战力 = _json_['血量特效战力']
        self.DPS特效战力 = _json_['DPS特效战力']
        self.基础总战力 = _json_['基础总战力']
        self.解锁技能数 = _json_['解锁技能数']
        self.技能列表 = _json_['技能列表']
        self.技能解锁后的总战力 = _json_['技能解锁后的总战力']
        self.对塔伤害 = _json_['对塔伤害']

class 生成数据_肉鸽技能选择节奏_1导 :
    def __init__(self, _json_):
        self.肉鸽技能升级次数 = _json_['肉鸽技能升级次数']
        self.理论所需经验值 = _json_['理论所需经验值']
        self.玩家消除行数 = _json_['玩家消除行数']
        self.玩家获得的经验总值 = _json_['玩家获得的经验总值']
        self.获得经验的时间_s = _json_['获得经验的时间_s']
        self.时间取整每30s = _json_['时间取整每30s']
        self.根据时间计数 = _json_['根据时间计数']
        self.怪物波次模拟 = _json_['怪物波次模拟']
        self.选择技能次数 = _json_['选择技能次数']
        self.总次数 = _json_['总次数']

class 生成数据_所有阵容强度战力成长时间分布表_1导 :
    def __init__(self, _json_):
        self.阵容强度和波次 = _json_['阵容强度和波次']
        self.阵容强度 = _json_['阵容强度']
        self.时间点_30s = _json_['时间点_30s']
        self.选技能次数 = _json_['选技能次数']
        self.总次数 = _json_['总次数']
        self.消除倍率 = _json_['消除倍率']
        self.每块小兵增加期望值 = _json_['每块小兵增加期望值']
        self.初始战力 = _json_['初始战力']
        self.当前阵容战力 = _json_['当前阵容战力']
        self.战力产出效率 = _json_['战力产出效率']
        self.每波怪物总战力 = _json_['每波怪物总战力']
        self.平均相当于多少个上阵角色 = _json_['平均相当于多少个上阵角色']

class 生成数据_战斗型Boss属性表_3导 :
    def __init__(self, _json_):
        self.怪物名称等级 = _json_['怪物名称等级']
        self.怪物编号 = _json_['怪物编号']
        self.等级 = _json_['等级']
        self.血量 = _json_['血量']
        self.攻击力 = _json_['攻击力']
        self.攻速 = _json_['攻速']
        self.攻击范围 = _json_['攻击范围']
        self.移动速度 = _json_['移动速度']
        self.DPS = _json_['DPS']
        self.血量特效倍率 = _json_['血量特效倍率']
        self.DPS特效倍率 = _json_['DPS特效倍率']
        self.战力 = _json_['战力']
        self.品质 = _json_['品质']
        self.职业 = _json_['职业']
        self.名称 = _json_['名称']
        self.血量成长倍率 = _json_['血量成长倍率']
        self.攻击力成长倍率 = _json_['攻击力成长倍率']
        self.适配地图 = _json_['适配地图']
        self.对塔伤害 = _json_['对塔伤害']
        self.和理论值对比 = _json_['和理论值对比']
        self.血量倍数 = _json_['血量倍数']
        self.攻击力倍数 = _json_['攻击力倍数']

class 资源数据 :
    def __init__(self, _json_):
        self.类型 = _json_['类型']
        self.数值 = _json_['数值']
        self.浮动范围 = _json_['浮动范围']

class EnemyGroup :
    def __init__(self, _json_):
        self.enemy_id = _json_['enemy_id']
        self.enemy_count = _json_['enemy_count']
        self.current_level = _json_['current_level']
        self.reset_hp = _json_['reset_hp']
        self.time_between_enemies = _json_['time_between_enemies']
        self.time_between_groups = _json_['time_between_groups']

class LevelData_Level :
    def __init__(self, _json_):
        self.level_id = _json_['level_id']
        self.time_before_spawn = _json_['time_before_spawn']
        self.wave_list = []
        for _ele0_ in _json_['wave_list']:
            _e0_ = WaveData(_ele0_)
            self.wave_list.append(_e0_)

class vector2 :
    def __init__(self, _json_):
        self.x = _json_['x']
        self.y = _json_['y']

class vector3 :
    def __init__(self, _json_):
        self.x = _json_['x']
        self.y = _json_['y']
        self.z = _json_['z']

class vector4 :
    def __init__(self, _json_):
        self.x = _json_['x']
        self.y = _json_['y']
        self.z = _json_['z']
        self.w = _json_['w']

class WaveData :
    def __init__(self, _json_):
        self.enemy_group_list = []
        for _ele0_ in _json_['enemy_group_list']:
            _e0_ = EnemyGroup(_ele0_)
            self.enemy_group_list.append(_e0_)
        self.time_between_waves = _json_['time_between_waves']


class LevelData_TbLevel:

    def __init__(self, _json_ ):
        self._dataMap = {}
        self._dataList = []
        
        for _json2_ in _json_:
            _v = LevelData_Level(_json2_)
            self._dataList.append(_v)
            self._dataMap[_v.level_id] = _v

    def getDataMap(self) : return self._dataMap
    def getDataList(self) : return self._dataList

    def get(self, key) : return self._dataMap.get(key)

class 基础数据_Tb怪物设计表:

    def __init__(self, _json_ ):
        self._dataMap = {}
        self._dataList = []
        
        for _json2_ in _json_:
            _v = 基础数据_怪物设计表(_json2_)
            self._dataList.append(_v)
            self._dataMap[_v.怪物编号] = _v

    def getDataMap(self) : return self._dataMap
    def getDataList(self) : return self._dataList

    def get(self, key) : return self._dataMap.get(key)

class 基础数据_Tb消除倍率表:

    def __init__(self, _json_ ):
        self._dataMap = {}
        self._dataList = []
        
        for _json2_ in _json_:
            _v = 基础数据_消除倍率表(_json2_)
            self._dataList.append(_v)
            self._dataMap[_v.消除效率维度] = _v

    def getDataMap(self) : return self._dataMap
    def getDataList(self) : return self._dataList

    def get(self, key) : return self._dataMap.get(key)

class 基础数据_Tb游戏基本参数:

    def __init__(self, _json_ ):
        self._dataMap = {}
        self._dataList = []
        
        for _json2_ in _json_:
            _v = 基础数据_游戏基本参数(_json2_)
            self._dataList.append(_v)
            self._dataMap[_v.每个方块的小方块数] = _v

    def getDataMap(self) : return self._dataMap
    def getDataList(self) : return self._dataList

    def get(self, key) : return self._dataMap.get(key)

class 基础数据_Tb玩家操作评估:

    def __init__(self, _json_ ):
        self._dataMap = {}
        self._dataList = []
        
        for _json2_ in _json_:
            _v = 基础数据_玩家操作评估(_json2_)
            self._dataList.append(_v)
            self._dataMap[_v.平均一个方块下几秒] = _v

    def getDataMap(self) : return self._dataMap
    def getDataList(self) : return self._dataList

    def get(self, key) : return self._dataMap.get(key)

class 基础数据_Tb经济系统配置表:

    def __init__(self, _json_ ):
        self._dataMap = {}
        self._dataList = []
        
        for _json2_ in _json_:
            _v = 基础数据_经济系统配置表(_json2_)
            self._dataList.append(_v)
            self._dataMap[_v.经济系统] = _v

    def getDataMap(self) : return self._dataMap
    def getDataList(self) : return self._dataList

    def get(self, key) : return self._dataMap.get(key)

class 基础数据_Tb肉鸽技能数据表:

    def __init__(self, _json_ ):
        self._dataMap = {}
        self._dataList = []
        
        for _json2_ in _json_:
            _v = 基础数据_肉鸽技能数据表(_json2_)
            self._dataList.append(_v)
            self._dataMap[_v.肉鸽技能名称] = _v

    def getDataMap(self) : return self._dataMap
    def getDataList(self) : return self._dataList

    def get(self, key) : return self._dataMap.get(key)

class 基础数据_Tb角色初始属性表:

    def __init__(self, _json_ ):
        self._dataMap = {}
        self._dataList = []
        
        for _json2_ in _json_:
            _v = 基础数据_角色初始属性表(_json2_)
            self._dataList.append(_v)
            self._dataMap[_v.角色名称] = _v

    def getDataMap(self) : return self._dataMap
    def getDataList(self) : return self._dataList

    def get(self, key) : return self._dataMap.get(key)

class 基础数据_Tb角色技能数据表:

    def __init__(self, _json_ ):
        self._dataMap = {}
        self._dataList = []
        
        for _json2_ in _json_:
            _v = 基础数据_角色技能数据表(_json2_)
            self._dataList.append(_v)
            self._dataMap[_v.角色名称] = _v

    def getDataMap(self) : return self._dataMap
    def getDataList(self) : return self._dataList

    def get(self, key) : return self._dataMap.get(key)

class 生成数据_Tb关卡设计表_1导:

    def __init__(self, _json_ ):
        self._dataMap = {}
        self._dataList = []
        
        for _json2_ in _json_:
            _v = 生成数据_关卡设计表_1导(_json2_)
            self._dataList.append(_v)
            self._dataMap[_v.关卡编号] = _v

    def getDataMap(self) : return self._dataMap
    def getDataList(self) : return self._dataList

    def get(self, key) : return self._dataMap.get(key)

class 生成数据_Tb怪物基础数据表_3导:

    def __init__(self, _json_ ):
        self._dataMap = {}
        self._dataList = []
        
        for _json2_ in _json_:
            _v = 生成数据_怪物基础数据表_3导(_json2_)
            self._dataList.append(_v)
            self._dataMap[_v.怪物名称等级] = _v

    def getDataMap(self) : return self._dataMap
    def getDataList(self) : return self._dataList

    def get(self, key) : return self._dataMap.get(key)

class 生成数据_Tb战斗型Boss属性表_3导:

    def __init__(self, _json_ ):
        self._dataMap = {}
        self._dataList = []
        
        for _json2_ in _json_:
            _v = 生成数据_战斗型Boss属性表_3导(_json2_)
            self._dataList.append(_v)
            self._dataMap[_v.怪物名称等级] = _v

    def getDataMap(self) : return self._dataMap
    def getDataList(self) : return self._dataList

    def get(self, key) : return self._dataMap.get(key)

class 生成数据_Tb所有阵容强度战力成长时间分布表_1导:

    def __init__(self, _json_ ):
        self._dataMap = {}
        self._dataList = []
        
        for _json2_ in _json_:
            _v = 生成数据_所有阵容强度战力成长时间分布表_1导(_json2_)
            self._dataList.append(_v)
            self._dataMap[_v.阵容强度和波次] = _v

    def getDataMap(self) : return self._dataMap
    def getDataList(self) : return self._dataList

    def get(self, key) : return self._dataMap.get(key)

class 生成数据_Tb技能型Boss属性表_3导:

    def __init__(self, _json_ ):
        self._dataMap = {}
        self._dataList = []
        
        for _json2_ in _json_:
            _v = 生成数据_技能型Boss属性表_3导(_json2_)
            self._dataList.append(_v)
            self._dataMap[_v.名称] = _v

    def getDataMap(self) : return self._dataMap
    def getDataList(self) : return self._dataList

    def get(self, key) : return self._dataMap.get(key)

class 生成数据_Tb肉鸽技能选择节奏_1导:

    def __init__(self, _json_ ):
        self._dataMap = {}
        self._dataList = []
        
        for _json2_ in _json_:
            _v = 生成数据_肉鸽技能选择节奏_1导(_json2_)
            self._dataList.append(_v)
            self._dataMap[_v.肉鸽技能升级次数] = _v

    def getDataMap(self) : return self._dataMap
    def getDataList(self) : return self._dataList

    def get(self, key) : return self._dataMap.get(key)

class 生成数据_Tb角色成长数据_1导:

    def __init__(self, _json_ ):
        self._dataMap = {}
        self._dataList = []
        
        for _json2_ in _json_:
            _v = 生成数据_角色成长数据_1导(_json2_)
            self._dataList.append(_v)
            self._dataMap[_v.角色名称] = _v

    def getDataMap(self) : return self._dataMap
    def getDataList(self) : return self._dataList

    def get(self, key) : return self._dataMap.get(key)



class cfg_Tables:
    def __init__(self, loader):
        self.TbLevel = LevelData_TbLevel(loader('leveldata_tblevel')); 
        self.Tb怪物设计表 = 基础数据_Tb怪物设计表(loader('基础数据_tb怪物设计表')); 
        self.Tb消除倍率表 = 基础数据_Tb消除倍率表(loader('基础数据_tb消除倍率表')); 
        self.Tb游戏基本参数 = 基础数据_Tb游戏基本参数(loader('基础数据_tb游戏基本参数')); 
        self.Tb玩家操作评估 = 基础数据_Tb玩家操作评估(loader('基础数据_tb玩家操作评估')); 
        self.Tb经济系统配置表 = 基础数据_Tb经济系统配置表(loader('基础数据_tb经济系统配置表')); 
        self.Tb肉鸽技能数据表 = 基础数据_Tb肉鸽技能数据表(loader('基础数据_tb肉鸽技能数据表')); 
        self.Tb角色初始属性表 = 基础数据_Tb角色初始属性表(loader('基础数据_tb角色初始属性表')); 
        self.Tb角色技能数据表 = 基础数据_Tb角色技能数据表(loader('基础数据_tb角色技能数据表')); 
        self.Tb关卡设计表_1导 = 生成数据_Tb关卡设计表_1导(loader('生成数据_tb关卡设计表_1导')); 
        self.Tb怪物基础数据表_3导 = 生成数据_Tb怪物基础数据表_3导(loader('生成数据_tb怪物基础数据表_3导')); 
        self.Tb战斗型Boss属性表_3导 = 生成数据_Tb战斗型Boss属性表_3导(loader('生成数据_tb战斗型boss属性表_3导')); 
        self.Tb所有阵容强度战力成长时间分布表_1导 = 生成数据_Tb所有阵容强度战力成长时间分布表_1导(loader('生成数据_tb所有阵容强度战力成长时间分布表_1导')); 
        self.Tb技能型Boss属性表_3导 = 生成数据_Tb技能型Boss属性表_3导(loader('生成数据_tb技能型boss属性表_3导')); 
        self.Tb肉鸽技能选择节奏_1导 = 生成数据_Tb肉鸽技能选择节奏_1导(loader('生成数据_tb肉鸽技能选择节奏_1导')); 
        self.Tb角色成长数据_1导 = 生成数据_Tb角色成长数据_1导(loader('生成数据_tb角色成长数据_1导')); 

